import PolicyPage, { type PolicySection } from "../components/PolicyPage";
import BreadcrumbSchema from "../components/seo/BreadcrumbSchema";
import { usePageMeta } from "../lib/seo";

const sections: PolicySection[] = [
  { title: "Scope of this notice", body: ["This notice describes the public website and the information you choose to provide when you call, email, text, mail, or visit Rafla Insurance Agency. It does not replace a carrier privacy notice, a policy document, or any separate financial-privacy notice that may apply when an insurance relationship is created."] },
  { title: "No online insurance submission", body: ["This website does not ask you to create an account, upload insurance documents, or enter driver, property, payment, or policy information into an online form. The quote preparation guide only shows a checklist and direct contact options; your selections are not transmitted or saved."], bullets: ["Do not send Social Security numbers, payment-card data, medical records, or full driver’s-license images through ordinary email or text.", "An email, text, or website interaction does not bind, amend, or guarantee coverage."] },
  { title: "Information you choose to share", body: ["When you contact the agency directly, it may receive the details you provide. Depending on your request, that can include contact information and information about drivers, vehicles, property, household members, business operations, insurance history, or a coverage need."], bullets: ["The agency may use that information to respond, prepare or discuss a quote, communicate with insurers or service providers involved in the request, maintain required business records, prevent misuse, and meet legal or regulatory obligations."] },
  { title: "Website hosting and measurement", body: ["Vercel hosts the site and provides Web Analytics and Speed Insights. Web Analytics records aggregate page-view information without third-party advertising cookies or cross-site identifiers. Measurement data may include the page or route visited, referral source, general geographic region, device type, operating system, browser, and timestamp. Hosting and security logs may also process an IP address and requested URL to deliver and protect the site."], bullets: ["The agency does not send contact, quote, driver, property, or policy details to website analytics.", "The public website does not use analytics data for cross-context behavioral advertising.", "Third-party maps, review pages, phone, email, or text services are governed by their own privacy practices."] },
  { title: "Insurance records and other notices", body: ["Quote, application, policy, billing, and claim information handled by the agency or an insurance carrier may be subject to separate insurance, financial-privacy, security, retention, and regulatory requirements. Any privacy notice delivered for that relationship governs those records in addition to applicable law."] },
  { title: "Retention and security", body: ["Information is retained as reasonably needed for the request, agency records, legal obligations, fraud prevention, or dispute resolution. The agency uses reasonable administrative and technical measures appropriate to the information, but no internet transmission or storage system can be guaranteed completely secure. Use the phone or in-person office for sensitive matters."] },
  { title: "Your choices and requests", body: ["You can browse without contacting the agency and may call or visit instead of using email or text. Depending on the law and the information involved, California residents may have rights to request access, correction, or deletion and to receive information about certain data practices. Some insurance records may be exempt or may need to be retained. The agency may verify identity before acting on a request and will not discriminate for exercising an applicable privacy right."], bullets: ["Rafla does not sell personal information submitted through this public website.", "To make a privacy request, use the phone, email, or mailing address below."] },
  { title: "Contact", body: ["Questions about this notice can be directed to Rafla Insurance Agency at (310) 572-7246 or contact@raflainsurance.com, or by mail at 12240 Venice Blvd, Suite 2, Los Angeles, CA 90066."] },
];

export default function Privacy() {
  usePageMeta({ title: "Privacy & Data Handling | Rafla Insurance Agency", description: "How Rafla Insurance Agency handles information submitted through its Los Angeles insurance website and contact channels.", canonical: "https://raflainsurance.com/privacy" });
  return <><BreadcrumbSchema crumbs={[{ name: "Home", url: "https://raflainsurance.com/" }, { name: "Privacy", url: "https://raflainsurance.com/privacy" }]} /><PolicyPage code="P1" eyebrow="Privacy & data handling" title="Clear expectations for the information you share." lede="This notice describes the public website and agency contact channels. Carrier notices and policy documents may contain additional terms." updated="August 27, 2026" sections={sections} /></>;
}
